### ISSUE TITLE
Please elaborate nvdla_compiler for nv_small.

### ISSUE THREAD

**Issue by kanghanbich** [nvdla/sw#141] opened 2019-05-30 01:31 UTC
hi,
I am trying to activate MNIST with nv_small(int8) version using updated sw.
But if I run the fast-path.nvdla file, I'd like to get help because I get an error.

I made a fast-path.nvdla file by inputting lenet.prototxt and lenet_itro_10000.caffemodel.
The command I entered is as follows:
![3](https://user-images.githubusercontent.com/40628811/58600277-eb9f6600-82be-11e9-968c-dfc9355d8114.PNG)
(image 1)

I read on Issues that options  --calibtable, --quantizationMode should also be applied,
but i don't understand how to apply them, even if i read LowPrecision.md.
![2](https://user-images.githubusercontent.com/40628811/58601662-d0cff000-82c4-11e9-9d93-d37924586d6f.PNG)
(image 2)

When i enter a fast-math.nvdla file created by the command(image1) that entered,
the following statement is generated:
![4](https://user-images.githubusercontent.com/40628811/58601884-b4808300-82c5-11e9-97f8-628c5cc075da.PNG)

I'd like to get some help on this part. Is it possible?

**Comment by prasshantg** [comment] 2019-05-30 15:43
Let me share you sample calibration table. Give me a day.

**Comment by prasshantg** [comment] 2019-06-02 18:06
Duplicate of #140

**Closed by prasshantg** 2019-06-02 18:06 UTC
Labels: duplicate
