### ISSUE TITLE
how to install SW in QEMU

### ISSUE THREAD

**Issue by ShoneAlbert** [nvdla/sw#3] opened 2017-12-14 11:26 UTC
According to the doc, I have installed Qbox in my machine. And I can run "hello world". But how to install SW in it. 
And if I have a caffe model , the ptotxt file and how to continue the  inference process.

**Comment by wujunning2011** [comment] 2017-12-15 02:07
good question, waiting for it!

**Comment by jwise** [comment] 2017-12-15 07:20
I think this is a duplicate of nvdla/vp#1; I'll close it as such.  (In the future, you only need to open one ticket per issue.)  Thanks for your interest in NVDLA!

**Closed by jwise** 2017-12-15 07:20 UTC
