### ISSUE TITLE
Compiling ResNet fails 

### ISSUE THREAD

**Issue by ned-varnica** [nvdla/sw#16] opened 2018-01-23 02:45 UTC
Hi, When I try to compile ResNets (e.g. ResNet-18): 

nvdla_compiler --prototxt ResNet18deploy.prototxt --caffemodel resnet18.caffemodel -o compileOutNvdla

I get the following Error message:  

creating new wisdom context...
opening wisdom context...
parsing caffe network...
Marking output [0] for layer fc1000
attaching parsed network to the wisdom...
compiling profile "default"...
libnvdla<3> compile network
libnvdla<3> compile201
(DLA) Error 0x00000004: Proposed surf format:NVDLA_FEATURE_DATA_FP16 is not supported by node:ew-0 (propagating from engine-ast/EngineNode.cpp, function supportsSurfaceFormat(), line 214)
(DLA) Error 0x00000004: (propagating from engine-ast/EngineNode.cpp, function verifyInputSurfaceFormats(), line 254)
(DLA) Error 0x00000004: (propagating from engine-ast/EngineGraph.cpp, function registerAllSurfaces(), line 602)
(DLA) Error 0x00000004: (propagating from Compiler.cpp, function registerBuffers(), line 1015)
(DLA) Error 0x00000008: failed compilation phase: registerBuffers (propagating from Compiler.cpp, function compile(), line 261)
(DLA) Error 0x00000004: compiler->compile("default") failed (in CompileTest.cpp, function compileProfile(), line 48)
(DLA) Error 0x00000004: (propagating from ParseTest.cpp, function parseAndCompile(), line 174)
(DLA) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 79)

Anybody knows how to resolve this (or had success compiling another ResNet)?  Does this mean that 'Eltwise' layer is currently not supported?  Thanks!   (Attached is the ResNet18deploy.prototxt I used) 

[ResNet18deploy.txt](https://github.com/nvdla/sw/files/1657360/ResNet18deploy.txt)

**Comment by prasshantg** [comment] 2018-02-06 12:00
@ned-varnica currently eltwise layer is not supported in NVDLA compiler, we are working on it.

**Comment by ned-varnica** [comment] 2018-02-06 21:12
Ok, great.  Thanks for the confirmation.

**Comment by prasshantg** [comment] 2018-04-24 17:28
@ned-varnica can you please share your caffemodel for ResNet? I want to verify it with our updated compiler

**Comment by nedvarnica** [comment] 2018-04-24 20:12
Hi **@prasshantg** 

The caffemodel we are using can be found here: 

https://drive.google.com/file/d/0B_geeR2lTMegUzlSdG5wZ1V5WU0/view

The corresponding prototxt file:
  
https://github.com/ydwen/caffe-face/blob/caffe-face/face_example/face_deploy.prototxt

**Comment by prasshantg** [comment] 2018-04-26 05:28
Hi @ned-varnica 

We have released latest compiler which enables ResNet. Kindly update all software components including compiler, runtime and kmd to test ResNet.

Please note, compiler PReLU is not yet supported so you will have to use ReLU for testing. PReLU is planned for next release.

**Comment by ned-varnica** [comment] 2018-04-26 18:59
Hi **@prasshantg** 

Thanks very much.  Much appreciated.  Will try several ResNets and let you know our results.  

Thanks for the update about PReLU, too.

**Comment by ned-varnica** [comment] 2018-04-26 19:15
update: We were able to compile a small ResNet (with 18 layers and ReLU) cleanly.  We kicked off a test on the Virtual Platform.  This is still running.  Will keep you posted.

**Comment by ned-varnica** [comment] 2018-04-27 02:17
Hi **@prasshantg** 

We have an update and 2 questions:  

Update:  The test on Virtual Platform runs and finishes without any issues. This is great. Thanks!  
Unfortunately, the output file does not produce what we expect to see with the given input.  

For example, we ran it with the following ".jpg" image of a boat
![boatres224x224](https://user-images.githubusercontent.com/35714770/39340520-70813c2a-4983-11e8-97d2-9198898f5ac1.jpg)
The ResNet-18 network we use is trained for ImageNet data-set.  The caffemodel can be found here  
https://onedrive.live.com/?authkey=%21ANF8hWlK9D8LGrk&cid=7C725726AF404CFD&id=7C725726AF404CFD%21110&parId=root&o=OneUp
Prototxt file: 
[ResNet-18-deploy.prototxt.txt](https://github.com/nvdla/sw/files/1953625/ResNet-18-deploy.prototxt.txt)

Our run on NVDLA Virtual Platform produced the output file attached here:    
[20180426_ResNet-18_BoatRes224x224.dimg.txt](https://github.com/nvdla/sw/files/1953558/20180426_ResNet-18_BoatRes224x224.dimg.txt)
Inspecting this file shows that the top categories (largest probabilities) are in entries 421 and 643 of the output file. These 2 entries (421 and 643) correspond to categories not related to the object we are trying to identify ("boat").  FYI, the 1000 categories of ImageNet data-set are attached here
[synset_words.txt](https://github.com/nvdla/sw/files/1953562/synset_words.txt)

On the other hand, if we run the same ResNet network in our local SW tool (python/caffe), we get the outputs as in the attached file here  
[OutputforBoatJPG.txt](https://github.com/nvdla/sw/files/1953573/OutputforBoatJPG.txt)
These outputs are predicting correctly that this is "speedboat":  the largest probability in this file is the entry 815 (corresponding to the category "speedboat" -- This can be seen by checking entry 815 in the "synset_words.txt" file) .  

Question 1: We are not too concerned with the Virtual Platform not producing correct result, as long this is a non-issue on FPGA platform.  So, our question is:  Should we expect the same result once we port the system on FPGA (we are in the process of doing so)?  If the same issue with outputs is expected there, we would appreciate so much if you could help us in resolving this issue soon.    

Question 2:   Do you have a test case with ResNet (or AlexNet) where you ran a particular input image and found that the outputs are good, i.e. correctly classifying objects of interest?  If so, could you please share that?  

thanks again!

**Comment by prasshantg** [comment] 2018-04-27 04:11
@ned-varnica do you have mean data for the image database that you are using? want to verify if mismatch is because we are not subtracting mean from image before processing

**Comment by ned-varnica** [comment] 2018-04-27 18:48
Hi **@prasshantg** 

Yes, the RGB means are [104,007 116.669 122.679].  However, we are not seeing that this changes things fundamentally: We tried in our SW (python+caffe) simulator to (deliberately) not subtract means: This changes output probabilities but we can still recognize that the image contains a boat (the top two categories in this case are 629 and 815 (these correspond to "ocean liner" and "speedboat", respectively.) 

This suggests that there are other issues present, especially given that the similar issues were observed with AlexNet. Please see the last six comments here   
https://github.com/nvdla/sw/issues/9 

That was our observation for AlexNet. I also looked at the output file that JunningWu provided: This file also shows that the object he tried ("cat") could not be identified.    

Please let us know if we can provide any additional info.  Thanks!

**Comment by ned-varnica** [comment] 2018-05-11 02:08
Hi, any update on the output issues (please see above)?  

Please let us know if any additional info is needed.  Thanks again!

**Comment by prasshantg** [comment] 2018-05-12 12:17
@ned-varnica we are debugging this issue, will get back next week.

**Comment by nvarnica** [comment] 2018-05-12 20:05
**@prasshantg**  Thanks, much appreciated!

**Comment by ned-varnica** [comment] 2018-05-21 18:34
Hi @prasshantg  
Any update?  We can provide additional outputs if you find that helpful. For example, we could provide the data at different layers of the network (that we run in Caffe), if needed.

**Comment by smsharif1991** [comment] 2018-05-22 05:51
Hi @ned-varnica ,
Sorry for the late reply, we are looking into it and will get back to you in this week.
Will ask for more data if needed.

Thanks.

**Comment by ned-varnica** [comment] 2018-05-22 19:52
Hi *smsharif1991* , 
thanks for the update. Much appreciated!

**Comment by smsharif1991** [comment] 2018-05-25 07:28
Hi @ned-varnica ,
Could you help provide the data at different layers of the network (Caffe)??

Thanks.

**Comment by ned-varnica** [comment] 2018-05-25 23:35
Hi **@smsharif1991**

Yes, the training was done on mean subtracted images.  Please see the earlier message in this thread (from 28 days ago): "The RGB means are [104,007 116.669 122.679]...." At that time, we tried doing inference in Caffe with means **not** subtracted (removed that step deliberately) to check whether the means are the main issue: The conclusion was that feeding such image in Caffe was still giving pretty good results and was not close to matching what we see with Nvdla.  So, it can't be just the means.  

Do you think there could be other issues with input (e.g. any scaling we need to be aware of, etc)?    BTW, the network was trained with image data being in the range 0-255 (and means were subtracted, as you pointed out).  

Given that we don't anticipate this is the only issue, can we go ahead with 1. from your message?  Here is our python script that runs the same ResNet (please remove the .txt extension from the filename) 

[InferenceResNet18_OneFrame.py.txt]
(https://github.com/nvdla/sw/files/2041097/InferenceResNet18_OneFrame.py.txt)

An example how to call the attached python script:  

python InferenceResNet18_OneFrame.py  -i Boat.jpg  

Please let us know if you have any questions regarding the script, or about how to get the data at different layers, etc.   (An example of this is provided near the bottom of the script).  

All the files (including one input image of a 'boat') necessary to run this script were provided in the message sent 29 days ago in this thread.  Please see that message and let us know if you have any questions.  

We look forward and appreciate your help and feedback.  Thanks!

**Comment by prasshantg** [comment] 2018-06-01 15:15
@ned-varnica we figured out that issue is related to pre-processing. We have added option to specify value for normalization in test application. Please try using "--normalize 1.0" with **ResNet-50** model. Looks like ResNet-18 model requires some more pre-processing steps that we are missing in our test application. We are looking into it but you can continue using ResNet-50 till then.

**Comment by ned-varnica** [comment] 2018-06-01 23:13
**@prasshantg**   Thanks very much.  We tried ResNet-50 and it works very well.  Much appreciated!  

Pls let us know if there is anything we can do to help with ResNet-18.

**Comment by ned-varnica** [comment] 2018-06-15 01:55
Hi @prasshantg  

Any update on getting ResNet-18 to produce expected results?  

Thanks! 
p.s. At this point, we confirmed on many examples that ResNet-50 works very well, but we are struggling for speed (hence ResNet-18 would be very helpful).

**Comment by prasshantg** [comment] 2018-06-15 03:00
@ned-varnica we have partially root caused to incorrect parsing of BN layer in ResNet-18 which is bit different than ResNet-50 but not verified the theory yet. We should have some fix by next week.

Also, we are working on cache sync operations to improve speed.

**Comment by ned-varnica** [comment] 2018-06-25 07:13
Hi @prasshantg 

Any update on ResNet-18 or on cache sync operations progress? Thanks very much!

**Comment by ned-varnica** [comment] 2018-06-28 01:58
Hi @prasshantg 

Great, thanks!

**Comment by prasshantg** [comment] 2018-06-28 16:41
@ned-varnica good news for you, we have root caused issue and verified that results are correct for ResNet-18 model. Also, we are able to improve execution time on VP. We will release these fixes in next 2-3 days excluding weekend.

**Comment by ned-varnica** [comment] 2018-07-07 03:43
Hi @prasshantg.  Have any updates been released yet?  Would appreciate any update you might have on the schedule for these.  Thanks!

**Comment by prasshantg** [comment] 2018-07-12 01:30
@ned-varnica fix released, please fetch TOT. Also, if you want to improve execution time then please fetch VP and rebuild it. Fix is released in HW tree for improving execution time.

**Comment by ned-varnica** [comment] 2018-07-18 02:00
Thanks so much @prasshantg .  It works very well.  Much appreciated!

**Closed** 2018-07-18 09:42 UTC
Labels: bug

**Comment by gitosu67** [comment] 2020-01-31 18:39
Can anyone provide the calibration file, the caffemodel and prototxt file for ResNet-18? It will help a lot, thanks!

**Comment by ghost** [comment] 2021-07-31 09:46
hello @prasshantg  I am unable to compile the UMD.can you please help me to solve that.
![image](https://user-images.githubusercontent.com/51146044/127735989-244906dc-da12-4551-b2f8-f9c3a8a5017a.png)
